# -----------------------------------------------
# Site Settings
# -----------------------------------------------
title: "Amalgam®"
tagline: "Language Reference and Examples."
description: "Official documentation for the Amalgam programming language."
url: "https://howsoai.github.io"
baseurl: "/amalgam"

remote_theme: just-the-docs/just-the-docs

# Theme settings
color_scheme: light  # "light" or "dark"

enable_copy_code_button: true

# Search
search_enabled: true

# Table of contents
defaults:
  - scope:
      path: ""
    values:
      toc: true

plugins:
  - jekyll-remote-theme