# This Gemfile is for GitHub Pages only (documentation deployment)

source "https://rubygems.org"

gem "jekyll"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-soopr-seo-tag"