name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      build-type:
        required: false
        type: string

defaults:
  run:
    shell: bash

jobs:

  build-linux:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/howsoai/amalgam-build-container-linux:2.0.8
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    strategy:
      matrix:
        preset:
          - arch: amd64
            platform: linux
            idx: 1
          - arch: amd64
            platform: linux
            idx: 2
          - arch: amd64
            platform: linux
            idx: 3
          - arch: amd64
            platform: linux
            idx: 4
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set build preset
      run: |
        PRESET=$(echo ${{ matrix.preset.arch }}-release-${{ matrix.preset.platform }})
        echo "PRESET=$(echo $PRESET)" >> $GITHUB_ENV
        echo "Build preset: $PRESET"
        ldd --version
        gcc --version
        cmake --version
        ninja --version

    - name: CMake Configure
      run: AMALGAM_BUILD_VERSION=${{ inputs.version }} cmake --preset $PRESET

    - name: CMake Build
      run: cmake --build --preset $PRESET --

    - name: CMake Test (GDB)
      run: |
          # Install GDB
          sudo apt-get install -y gdb
          echo "GDB installation complete"
          
          # Don't immediately fail if GDB exits with a non-zero code
          set +e

          #cp out/build/${{ matrix.preset.arch }}-release-${{ matrix.preset.platform }}/amalgam-mt-afmi ./src/Amalgam/
          #cd src/Amalgam && pwd && ls

          echo "Running tests..."

          # Capture GDB output
          #gdb_output=$(gdb -batch -ex run -ex "bt" --args ./amalgam-mt-afmi amlg_code/full_test.amlg)
          cd /__w/amalgam/amalgam/out/build/amd64-release-linux
          /usr/bin/ctest --force-new-ctest-process -L smoke_test -j --schedule-random --output-on-failure --extra-verbose --output-log /__w/amalgam/amalgam/out/test/all_tests.log
          exit 0
          #echo "$gdb_output" | tail -n 150

          # Evaluate GDB exit code and exit this workflow accordingly
          if echo "$gdb_output" | tail -n 100 | grep -q "exited normally"; then
            exit 0
          # Else, something failed, exit 1
          else
            exit 1
          fi
